product_spec_northstar: >
  Project Name: Quran Secrets Analyzer
  Purpose: Develop a Python application to search secrets of Quran. 
  
  *** Build a comprehensive ultimate Quran Analyzer program that analyzes whole Quranic text and finds ultimate secrets. ***
  Think and generate ideas about possible divine secrets and messages hidden, including but not limited to number 19. 
  In each development phase of the program, expand the search space to new arabic words in Quran, verses, surahs and search patterns.
  Start with arabic word and word groups that are in Quran but as you advanced look for more advanced patterns and search unthinkable secrets. 
  Create lemma and root word analysis using python libraries such as well known CAMeL and Arabic lemmatizer.
  Apply innovative new search ideas.
  There's no limit or restriction on what kind of search and analysis you can do on seeking the ultimate secrets of Quran.

  Data Source:
  You are given {project_root}/data/quran-uthmani-min.txt Do NOT modify this file. It is the source of truth and assume this file will always be there.
  Use this file in your program to do search and run analysis.
  Each line in the file represents a unique verse and specifies surah and ayah numbers. Here are the first three lines:
  1|1|بِسمِ اللَّهِ الرَّحمٰنِ الرَّحيمِ
  1|2|الحَمدُ لِلَّهِ رَبِّ العٰلَمينَ
  1|3|الرَّحمٰنِ الرَّحيمِ
  
  Normalize the arabic text by processing it before your analysis:
  1) Diacritics (e.g., اللَّهِ vs. الله)
  2) Slight character variants (e.g., ى vs ي)
  3) Possibly invisible Unicode differences
  Arabic has no uppercase/lowercase.

  Analysis and Search Strategy:
  *** Main function will be the ultimate driver of full analysis. It is not a test, example or demonstrations code. It must be through, verbose and fully complete Quran Analysis for finding ultimate Secrets. ***
  Create an integration test that will run Main function fully without any mock and run the program to extract secrets. Log the results to a file.
  If you find a secret make sure you tag it explicitly in the output with 'POTENTIAL SECRET FOUND:'. 


project_root_folder: C:\Github\secrets_of_quran
product_spec_history_filename: product_spec_history.json
architecture_spec_history_filename: architecture_spec_history.json
codebase_metadata_filename: codebase_metadata.json
total_runs_to_build_northstar: 20
max_test_attempts_per_iteration: 5
programming_languages:
  - python
development_os: "Windows 11"
run_tests: True
auto_commit: True
auto_revert: False
use_local_llm: False


